// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "nAPI",
            "endpoint": "https://aswacb6ln9.execute-api.us-east-1.amazonaws.com/react",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "pronoob-serverless-react",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d24mo18wp5yd2g.cloudfront.net"
};


export default awsmobile;
