// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "nAPI",
            "endpoint": "https://bzclj8rbch.execute-api.us-east-1.amazonaws.com/serverless",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "n-serverless-serverless",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://n-serverless-serverless.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
